### ISSUE TITLE
400 Bad Request

### ISSUE THREAD

**Issue by fangdajiang** [ica10888/k8s-terminal#3]
您好，运行报错： 

java.net.ProtocolException: Expected HTTP 101 response but was '400 Bad Request'
	at okhttp3.internal.ws.RealWebSocket.checkUpgradeSuccess(RealWebSocket.java:224)
	at okhttp3.internal.ws.RealWebSocket$1.onResponse(RealWebSocket.java:195)
	at okhttp3.RealCall$AsyncCall.execute(RealCall.java:174)
	at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

假如 namespace 或 container 随意写会报 404，那么我猜测认证已通过。

SpringWebSocketHandler.afterConnectionEstablished 的 connected 日志也能看到，之后就 400

烦请指点。

**Comment by fangdajiang** [comment]
发现是 container 名称写错导致的
